### ISSUE TITLE
Action fails with not found

### ISSUE THREAD

**Issue by SuperchupuDev** [biomejs/setup-biome#127]
> Error: Not Found - https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name

https://github.com/biomejs/discord-utils-bot/actions/runs/9246721400/job/25451892086#step:3:1

It worked just a few days ago

**Comment by nhedger** [comment]
Action is attempting to install 1.7.4 (stable) which hasn't yet been released.

**Comment by nhedger** [comment]
Fixed by 4b03a879910551492c58a03ff3afc35ba2d69992
