### ISSUE TITLE
Read version from `bun.lockb` binary file

### ISSUE THREAD

**Issue by nhedger** [biomejs/setup-biome#40]
The action currently relies on the user configuring Bun to output a human-readable `yarn.lock` file alongside its native `bun.lockb` binary file, which requires additional steps.

We'd like to explore the possibility of reading Bun's lockfile to extract the version of Biome, without having to install Bun.

**Comment by jbergstroem** [comment]
Another approach could be using the same "semver range" method of installing biome from reading `package.json` instead of the absolute lookup via lockfile? It should work for all package managers.

**Comment by nhedger** [comment]
Hey @jbergstroem, I also considered this initially, but we wouldn't know for sure if the latest version available in that range is actually the same version the user has installed locally.

From a version to the next, we may introduce fixes that slightly change the formatting or linting diagnostics, which I believe would break the CI.

**Comment by jbergstroem** [comment]
>  @nhedger said:
> I also considered this initially, but we wouldn't know for sure if the latest version available in that range is actually the same version the user has installed locally.

True; but they indirectly also say that they are willing to accept a semver range.

>  @nhedger said:
> From a version to the next, we may introduce fixes that slightly change the formatting or linting diagnostics, which I believe would break the CI.

That's the tricky part! What does "semver" mean in the eyes of biome. For instance; the `1.5.0` -> `1.5.1` had a bug with `useConsistentArrayType` that broke my setup locally (due to the config change).

No great anwers here other than that semver in the js ecosystem is not something reliable in my experience.

(also, sorry for hijacking this issue since its specific to bun)

**Comment by arendjr** [comment]
I would also be tempted to just look at the `package.json` and take it from there. We already advise users to put a specific version there, so as long as they do there should be no issue, regardless of package manager.

If they do configure a range however, we need to know what the latest version in that range is, which means the action also needs a list of published versions. Do is actually have this available?

**Comment by nhedger** [comment]
> I would also be tempted to just look at the `package.json` and take it from there. We already advise users to put a specific version there, so as long as they do there should be no issue, regardless of package manager.

I think you both make good points @jbergstroem, @arendjr. It's true that we already recommend pinning the version and that they indirectly accept a semver range.

> If they do configure a range however, we need to know what the latest version in that range is, which means the action also needs a list of published versions. Do it actually have this available?

The action already fetches all known releases from the GitHub API, so I believe we could reuse the data to retrieve the latest version in the range.

> PS.: I think it might even be a good idea to let the action print a warning if a range is configured to point users to the risk of breaking changes.

Love the idea!

**Comment by nhedger** [comment]
I've been thinking a bit about it, and here's what I've come up with.

- It attempts to read lockfiles if they are present and can be parsed
- It falls back to reading package.json otherwise
- It prints a warning if semver ranges are used

I'd appreciate any feedback.

![diagram-export-13-01-2024-12_12_53](https://github.com/biomejs/setup-biome/assets/649677/e392e8e8-c7d8-4cf1-b4f1-4bf79c27c490)

**Comment by jbergstroem** [comment]
> I'd appreciate any feedback.

Looks solid. Thanks for taking the time to put that together.

**Comment by nhedger** [comment]
Thanks for the feedback, let's get coding!
