### ISSUE TITLE
Suggestion: run with Bun

### ISSUE THREAD

**Issue by DaniGuardiola** [biomejs/setup-biome#44]
Bun is very fast, and it might speed this action up. It also requires no transpilation or bundling, it can run the ts files directly, so it should also help simplify this repo greatly. If building is still faster (which I doubt), then bun can do that too in a single command. Finally, given that the biome npm package is a thin wrapper over the Rust binary, it's unlikely to break. Because of this, I would suggest looking into this option for better speed :)

(I have not measured anything so I might be wrong!)

Edit: another advantage of this approach is that you'll be able to extract the version from bun's lockfile, since it'll be already installed.

**Comment by mountainash** [comment]
@DaniGuardiola it's bun/done #48

**Comment by nhedger** [comment]
Bun's moving to a non-binary lockfile shortly, which will solve this.
